@extends('layouts.app')

@section('content')
<div class="max-w-4xl mx-auto px-4 py-8">
    <div class="bg-white rounded-lg shadow-md p-6">
        <h2 class="text-2xl font-bold text-gray-800 mb-2">Booking for: {{ $schedule->movie->title }}</h2>
        <p class="text-gray-600 mb-6">
            <strong>Time:</strong> {{ $schedule->showtime->format('d M Y H:i') }} |
            <strong>Room:</strong> {{ $schedule->room ?? 'Main Theater' }}
        </p>

        <form method="POST" action="{{ route('booking.store') }}" id="bookingForm">
            @csrf
            <input type="hidden" name="schedule_id" value="{{ $schedule->id }}">
            <!-- Seats will be dynamically added as separate inputs -->

            <div class="text-center bg-gray-800 text-white py-2 rounded font-bold mb-6">
                LAYAR
            </div>

            <div class="flex justify-center mb-6">
                <div id="seats-container" class="max-w-2xl">
                    <!-- Seats will be dynamically generated by JavaScript -->
                </div>
            </div>

            <div class="flex justify-center gap-6 mb-6 text-sm">
                <div class="flex items-center gap-2">
                    <div class="w-6 h-6 bg-green-500 rounded flex items-center justify-center text-white text-xs">A</div>
                    <span>Available</span>
                </div>
                <div class="flex items-center gap-2">
                    <div class="w-6 h-6 bg-red-500 rounded flex items-center justify-center text-white text-xs">X</div>
                    <span>Booked</span>
                </div>
                <div class="flex items-center gap-2">
                    <div class="w-6 h-6 bg-blue-500 rounded flex items-center justify-center text-white text-xs">S</div>
                    <span>Selected</span>
                </div>
            </div>

            <div class="mb-6">
                <h5 class="text-lg font-semibold text-gray-700 mb-2">Selected Seats: <span id="selected-seats-count" class="text-indigo-600">0</span></h5>
                <div id="selected-seats-list" class="flex flex-wrap gap-2 mb-4"></div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                    <div>
                        <label for="customer_name" class="block text-sm font-medium text-gray-700 mb-1">Your Name</label>
                        <input type="text"
                               class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 @error('customer_name') border-red-500 @enderror"
                               id="customer_name" name="customer_name" required>
                        @error('customer_name')
                            <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>
                    <div>
                        <label for="customer_phone" class="block text-sm font-medium text-gray-700 mb-1">Phone Number</label>
                        <input type="text"
                               class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 @error('customer_phone') border-red-500 @enderror"
                               id="customer_phone" name="customer_phone" required>
                        @error('customer_phone')
                            <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                <div class="flex justify-end">
                    <button type="submit" class="bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-6 rounded-md" id="book-btn" disabled>
                        Confirm Booking
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    let selectedSeats = [];
    let bookedSeats = @json($bookedSeats) || [];
    let unavailableSeats = @json($unavailableSeats) || [];

    // Generate seat map based on total seats in the schedule
    function generateSeatMap() {
        const totalSeats = {{ $schedule->total_seats ?? $schedule->available_seats ?? 100 }}; // Fallback to available_seats or 100
        const seatsContainer = document.getElementById('seats-container');
        const seatsPerRow = 10; // Maximum 10 seats per row
        const rows = Math.ceil(totalSeats / seatsPerRow);

        let seatCount = 0;

        for (let row = 0; row < rows; row++) {
            const rowDiv = document.createElement('div');
            rowDiv.className = 'flex justify-center mb-2';

            for (let col = 0; col < seatsPerRow; col++) {
                seatCount++;
                if (seatCount > totalSeats) break; // Stop if we've reached total seats

                const seatLabel = String.fromCharCode(65 + row) + (col + 1); // A1, A2, ..., B1, B2, etc.

                const seatDiv = document.createElement('div');
                seatDiv.className = 'w-8 h-8 flex items-center justify-center m-1 cursor-pointer rounded font-bold text-sm transition-colors';
                seatDiv.textContent = seatLabel;
                seatDiv.dataset.seat = seatLabel;

                if (bookedSeats.includes(seatLabel) || unavailableSeats.includes(seatLabel)) {
                    seatDiv.className += ' bg-red-500 text-white cursor-not-allowed';
                    seatDiv.textContent = 'X';
                } else {
                    seatDiv.className += ' bg-green-500 text-white hover:bg-green-600';
                    seatDiv.addEventListener('click', function() {
                        toggleSeatSelection(this);
                    });
                }

                rowDiv.appendChild(seatDiv);
            }

            seatsContainer.appendChild(rowDiv);
        }
    }

    function updateSelectedSeats() {
        const count = selectedSeats.length;
        document.getElementById('selected-seats-count').textContent = count;

        const selectedList = document.getElementById('selected-seats-list');
        selectedList.innerHTML = '';

        if (count > 0) {
            // Show all selected seats in the list
            selectedSeats.forEach(seatNumber => {
                const seatBadge = document.createElement('span');
                seatBadge.className = 'inline-block bg-indigo-100 text-indigo-800 text-sm px-3 py-1 rounded-full';
                seatBadge.textContent = seatNumber;

                const removeBtn = document.createElement('button');
                removeBtn.type = 'button';
                removeBtn.className = 'ml-1 text-indigo-600 hover:text-indigo-800';
                removeBtn.innerHTML = '&times;';
                removeBtn.onclick = function() {
                    removeSeatSelection(seatNumber);
                };

                seatBadge.appendChild(removeBtn);
                selectedList.appendChild(seatBadge);
            });

            document.getElementById('book-btn').disabled = false;
        } else {
            document.getElementById('book-btn').disabled = true;
        }
    }

    function toggleSeatSelection(element) {
        if (element.classList.contains('bg-red-500')) return; // Don't allow selecting booked seats

        const seatLabel = element.dataset.seat;

        if (selectedSeats.includes(seatLabel)) {
            // Remove selection
            element.classList.remove('bg-blue-500', 'text-white');
            element.classList.add('bg-green-500', 'text-white', 'hover:bg-green-600');
            selectedSeats = selectedSeats.filter(seat => seat !== seatLabel);
        } else {
            // Add selection
            element.classList.remove('bg-green-500', 'hover:bg-green-600', 'text-white');
            element.classList.add('bg-blue-500', 'text-white');
            selectedSeats.push(seatLabel);
        }

        updateSelectedSeats();
    }

    function removeSeatSelection(seatNumber) {
        const seatElement = document.querySelector(`[data-seat="${seatNumber}"]`);
        if (seatElement && !seatElement.classList.contains('bg-red-500')) {
            seatElement.classList.remove('bg-blue-500', 'text-white');
            seatElement.classList.add('bg-green-500', 'text-white', 'hover:bg-green-600');
            selectedSeats = selectedSeats.filter(seat => seat !== seatNumber);
            updateSelectedSeats();
        }
    }

    // Handle form submission with proper seat locking
    document.getElementById('bookingForm').addEventListener('submit', async function(e) {
        e.preventDefault();

        if (selectedSeats.length === 0) {
            alert('Please select at least one seat.');
            return;
        }

        const customerName = document.getElementById('customer_name').value;
        const customerPhone = document.getElementById('customer_phone').value;

        if (!customerName || !customerPhone) {
            alert('Please fill in all required fields.');
            return;
        }

        // Remove any existing seat inputs to prevent duplicates
        const existingSeatInputs = document.querySelectorAll('input[name="seats[]"]');
        existingSeatInputs.forEach(input => input.remove());

        // Add hidden inputs for each selected seat BEFORE locking
        selectedSeats.forEach(seat => {
            const seatInput = document.createElement('input');
            seatInput.type = 'hidden';
            seatInput.name = 'seats[]';
            seatInput.value = seat;
            document.getElementById('bookingForm').appendChild(seatInput);
        });

        // Add payment method input
        let paymentInput = document.querySelector('input[name="payment_method"]');
        if (!paymentInput) {
            paymentInput = document.createElement('input');
            paymentInput.type = 'hidden';
            paymentInput.name = 'payment_method';
            paymentInput.value = 'dummy';
            document.getElementById('bookingForm').appendChild(paymentInput);
        } else {
            paymentInput.value = 'dummy';
        }

        try {
            // Get CSRF token safely
            const csrfToken = document.querySelector('meta[name="csrf-token"]');
            if (!csrfToken) {
                alert('CSRF token not found. Please refresh the page and try again.');
                return;
            }

            // Lock the selected seats
            const lockResponse = await fetch(`{{ route('booking.lock.seats', $schedule->id) }}`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': csrfToken.getAttribute('content'),
                    'Accept': 'application/json'
                },
                body: JSON.stringify({
                    seats: selectedSeats
                })
            });

            const lockResult = await lockResponse.json();

            if (lockResult.success) {
                // Submit the form after locking seats
                this.submit();
            } else {
                alert('Failed to lock seats: ' + lockResult.message);
                // Remove the seat inputs that were added since locking failed
                const newSeatInputs = document.querySelectorAll('input[name="seats[]"]');
                newSeatInputs.forEach(input => input.remove());
                // Reload page to refresh available seats
                location.reload();
            }
        } catch (error) {
            console.error('Error locking seats:', error);
            alert('Error: Failed to process booking. Please try again.');
        }
    });

    window.onload = function() {
        generateSeatMap();
    };
</script>
@endsection